# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d1a2c1b4bfc22486552326ce0932459"
name = "sr-upsell-bundle"
handle = "sr-upsell-bundle"
application_url = "https://d9a8-115-246-36-228.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "manoj-oscp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://d9a8-115-246-36-228.ngrok-free.app/auth/callback",
  "https://d9a8-115-246-36-228.ngrok-free.app/auth/shopify/callback",
  "https://d9a8-115-246-36-228.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
